AWSTemplateFormatVersion: 2010-09-09

Description: |
  This template creates an EC2 instance to run static web site with Apache web server.
  
Resources:
  Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-05fa00d4c63e32376
      InstanceType: t2.micro
      KeyName: cumhurkey
      SecurityGroups:
        - http-ssh-sec-grp
      Tags:
      - Key: Name
        Value: StackName ofWeb Server 
      UserData:
        Fn::Base64: |
           #!/bin/bash
           sudo yum update -y
           sudo yum install httpd -y
           sudo systemctl start httpd
           sudo systemctl enable httpd
           sudo yum install git -y 
           sudo chmod -R 777 /var/www/html
           cd /var/www/html
           git clone 